### ISSUE TITLE
polyfills possible breaks reflect-metadata

### ISSUE THREAD

**Issue by Tim-Erwin** [aurelia/polyfills#62]
(I don't know if this is the right repo to file this issue, aurelia-bootstrapper might be better.)

I was trying to use TypeScript's `reflect-metadata`, but never got back any of the metadata with

    Reflect.getMetadata('design:type', Bla.prototype, 'thing')

The problem is, that the reflect polyfill in this library is not compatible with the [original](https://www.npmjs.com/package/reflect-metadata) one.

I could fix this by importing `reflect-metadata` before `aurelia-bootstrapper` in my `app.ts`. I had a hard time tracking this down, so others might as well. It would be good to document this behavior somewhere, or make the polyfill compatible with the original or ... do we actually need a reflect polyfill in Aurelia?? There is an official library that needs to be used anyway (without it "`Reflect.getMetadata is not a function`").

**Comment by pkozul** [comment]
Had the same issue. Using Webpack, I added `reflect-metadata` to the `app` section (i.e. before `aurelia-bootstrapper`), which solved the problem for me.

```
module.exports = ({ production, server, extractCss, coverage, analyze } = {}) => ({
  resolve: {
    extensions: ['.ts', '.js'],
    modules: [srcDir, 'node_modules'],
  },
  entry: {
    app: ['reflect-metadata', 'aurelia-bootstrapper'],
    vendor: ['bluebird'],
  },
```

**Comment by sampaioletti** [comment]
Thanks @pkozul, that worked for me. Man that was frustrating and no amount of googling seemed to bring up a solution until i thought to check the polyfills and see if it was there.

**Comment by 4imble** [comment]
@pkozul Amazing, just wasted over an hour on this. 
The weird thing for me was on another project also Aurelia, all I had to do was import it at the top of my app.ts but this was not working here and I could not work out why. The webpack option is working a treat!

**Comment by peitschie** [comment]
This issue is actually happening with the command-line tool as well. The `aurelia-cli` module imports the polyfills into the process used for webpack building, breaking any webpack plugin that depends on `reflect-metadata`.

In my case, [webpack-obfuscator](https://github.com/javascript-obfuscator/webpack-obfuscator/tree/2.6.0) imports `reflect-metadata` (the full implementation) which results in the global `Reflect` object being a mixture of two polyfills which do not interop nicely.

This leads to the bug described at https://github.com/javascript-obfuscator/webpack-obfuscator/issues/41

Would it be possible to perhaps drop the partial `Reflect` implementation in `aurelia-polyfill` and instead switch to the very stable `reflect-metadata`?

**Comment by ff-will** [comment]
+1
I added the 'reflect-metadata' to the app entry before 'aurelia-bootstrap', but `Reflect.getMetadata()` still returns `undefined`. So for anyone who needs to add custom annotations for instance, aurelia-polyfill is a real show-stopper.

**Comment by Alexander-Taran** [comment]
webpack plugin has excellent docs in github wiki
https://github.com/aurelia/webpack-plugin/wiki/AureliaPlugin-options#features
one can disable some polyfills 
and looking @ https://github.com/aurelia/polyfills/blob/master/src/reflect.js I see that one can ditch reflect polyfilll from build output.

@bigopon I think this one can be closed..
